package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Strongbox</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:800px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.btn-d{border-color:var(--bg3);color:var(--cm)}.overview{display:flex;gap:1.5rem;margin-bottom:1rem;font-size:.7rem;color:var(--leather)}.overview .stat b{display:block;font-size:1.2rem;color:var(--cream)}.toolbar{display:flex;gap:.5rem;margin-bottom:.8rem;align-items:center}.toolbar select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.3rem .5rem;font-family:var(--mono);font-size:.72rem;outline:none}.sec-row{display:flex;align-items:center;gap:.5rem;padding:.4rem .5rem;border-bottom:1px solid var(--bg3);font-size:.75rem}.sec-name{font-weight:600;flex:1}.sec-val{color:var(--cm);font-style:italic;cursor:pointer}.sec-val.revealed{color:var(--cd);font-style:normal}.sec-env{font-size:.6rem;padding:.05rem .25rem;background:var(--bg3);color:var(--ll);border-radius:2px}.sec-ver{font-size:.6rem;color:var(--cm)}.tabs{display:flex;gap:0;margin-bottom:1rem;border-bottom:1px solid var(--bg3)}.tab{padding:.4rem 1rem;cursor:pointer;font-size:.75rem;color:var(--cm);border-bottom:2px solid transparent}.tab:hover{color:var(--cream)}.tab.active{color:var(--rl);border-bottom-color:var(--rl)}.audit-row{font-size:.72rem;padding:.25rem .5rem;border-bottom:1px solid var(--bg3);display:flex;gap:.5rem}.act-created{color:var(--green)}.act-updated{color:var(--gold)}.act-deleted{color:var(--red)}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],textarea,select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}textarea{resize:vertical;min-height:60px}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Strongbox</span></h1><button class="btn btn-p" onclick="showNew()">+ Secret</button></div>
<div class="main"><div class="overview" id="ov"></div>
<div class="tabs"><div class="tab active" data-tab="secrets" onclick="switchTab('secrets')">Secrets</div><div class="tab" data-tab="audit" onclick="switchTab('audit')">Audit Log</div></div>
<div id="pane-secrets"><div class="toolbar"><select id="envFilter" onchange="load()"><option value="">All environments</option></select><span style="flex:1"></span><span style="font-size:.65rem;color:var(--cm)">Values encrypted at rest (AES-256-GCM)</span></div><div id="list"></div></div>
<div id="pane-audit" style="display:none"><div id="auditList"></div></div>
</div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function timeAgo(d){if(!d)return'';const s=Math.floor((Date.now()-new Date(d))/1e3);if(s<60)return s+'s ago';if(s<3600)return Math.floor(s/60)+'m ago';return Math.floor(s/3600)+'h ago'}
async function init(){const[sd,ed]=await Promise.all([api('/api/stats'),api('/api/environments')]);
document.getElementById('ov').innerHTML='<div class="stat"><b>'+sd.secrets+'</b>Secrets</div><div class="stat"><b>'+sd.environments+'</b>Environments</div>';
const sel=document.getElementById('envFilter');sel.innerHTML='<option value="">All</option>'+((ed.environments||[]).map(e=>'<option>'+esc(e)+'</option>').join(''));load()}
async function load(){const env=document.getElementById('envFilter').value;const p=env?'?environment='+env:'';
const d=await api('/api/secrets'+p);const secs=d.secrets||[];
document.getElementById('list').innerHTML=secs.length?secs.map(s=>
'<div class="sec-row"><span class="sec-name">'+esc(s.name)+'</span><span class="sec-val" onclick="reveal(\''+s.id+'\',this)">'+esc(s.value)+'</span><span class="sec-env">'+esc(s.environment)+'</span><span class="sec-ver">v'+s.version+'</span><span style="cursor:pointer;font-size:.55rem;color:var(--cm)" onclick="del(\''+s.id+'\')">del</span></div>'
).join(''):'<div class="empty">No secrets yet. Values are encrypted with AES-256-GCM.</div>'}
async function reveal(id,el){if(el.classList.contains('revealed')){el.textContent='••••••••';el.classList.remove('revealed');return}
const s=await api('/api/secrets/'+id);el.textContent=s.value;el.classList.add('revealed')}
async function del(id){if(!confirm('Delete?'))return;await api('/api/secrets/'+id,{method:'DELETE'});load();init()}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Set Secret</h2><label class="fl">Name</label><input type="text" id="ns-name" placeholder="DATABASE_URL"><label class="fl">Value</label><textarea id="ns-val" rows="2" placeholder="postgres://..."></textarea><label class="fl">Environment</label><input type="text" id="ns-env" value="default"><label class="fl">Description</label><input type="text" id="ns-desc"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Set</button><button class="btn btn-d" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={name:document.getElementById('ns-name').value,value:document.getElementById('ns-val').value,environment:document.getElementById('ns-env').value||'default',description:document.getElementById('ns-desc').value};if(!b.name){alert('Name required');return};await api('/api/secrets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load();init()}
async function loadAudit(){const d=await api('/api/audit');document.getElementById('auditList').innerHTML=(d.audit||[]).map(a=>'<div class="audit-row"><span class="act-'+a.action+'" style="width:60px;font-weight:600">'+a.action+'</span><span style="flex:1;font-weight:600">'+esc(a.secret_name)+'</span><span style="color:var(--cm)">'+esc(a.actor||'-')+' · '+timeAgo(a.created_at)+'</span></div>').join('')||'<div class="empty">No audit entries.</div>'}
function switchTab(t){document.querySelectorAll('.tab').forEach(el=>el.classList.toggle('active',el.dataset.tab===t));document.getElementById('pane-secrets').style.display=t==='secrets'?'':'none';document.getElementById('pane-audit').style.display=t==='audit'?'':'none';if(t==='audit')loadAudit()}
function closeModal(){document.getElementById('modal').innerHTML=''}
init()
</script></body></html>`
