package server

var dashboardHTML = []byte(`<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Stockyard Strongbox</title><style>:root{--bg:#1a1410;--surface:#241c15;--border:#3d2e1e;--rust:#c4622d;--leather:#8b5e3c;--cream:#f5e6c8;--muted:#7a6550;--text:#e8d5b0}*{box-sizing:border-box;margin:0;padding:0}body{background:var(--bg);color:var(--text);font-family:'JetBrains Mono',monospace,sans-serif;min-height:100vh}header{background:var(--surface);border-bottom:1px solid var(--border);padding:1rem 2rem;display:flex;align-items:center;gap:1rem}.logo{color:var(--rust);font-size:1.25rem;font-weight:700}.badge{background:var(--rust);color:var(--cream);font-size:0.65rem;padding:0.2rem 0.5rem;border-radius:3px;font-weight:600;text-transform:uppercase}main{max-width:1100px;margin:0 auto;padding:2rem}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:2rem}.stat{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.25rem;text-align:center}.stat-value{font-size:1.75rem;font-weight:700;color:var(--rust)}.stat-label{font-size:0.75rem;color:var(--muted);margin-top:0.25rem;text-transform:uppercase;letter-spacing:0.05em}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.5rem}.card h2{font-size:0.85rem;color:var(--muted);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:1rem}.form-row{display:flex;gap:0.5rem;margin-bottom:0.75rem;flex-wrap:wrap;align-items:flex-start}select,input,textarea{background:var(--bg);border:1px solid var(--border);color:var(--text);padding:0.5rem 0.75rem;border-radius:4px;font-family:inherit;font-size:0.85rem}.form-row select,.form-row input{flex:1}textarea{width:100%;min-height:80px;resize:vertical}.btn{background:var(--rust);color:var(--cream);border:none;padding:0.5rem 1rem;border-radius:4px;cursor:pointer;font-family:inherit;font-size:0.85rem;font-weight:600}.btn:hover{opacity:0.85}.btn-sm{padding:0.25rem 0.6rem;font-size:0.75rem}.btn-danger{background:#7a2020}table{width:100%;border-collapse:collapse;font-size:0.82rem}th{text-align:left;color:var(--muted);padding:0.5rem;border-bottom:1px solid var(--border);font-size:0.75rem;text-transform:uppercase}td{padding:0.5rem;border-bottom:1px solid var(--border)}.empty{color:var(--muted);font-size:0.85rem;padding:1rem 0;text-align:center}.full{grid-column:1/-1}.bg{background:var(--bg);border:1px solid var(--border);border-radius:4px;padding:0.75rem;font-size:0.8rem;font-family:monospace;word-break:break-all}.badge-g{background:#1a3a1a;color:#5cb85c;border:1px solid #2d5a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-r{background:#3a1a1a;color:#d9534f;border:1px solid #5a2d2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-y{background:#3a2f1a;color:#f0ad4e;border:1px solid #5a4a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}</style></head>
<body><header><span class="logo">&#x2B21; Stockyard</span><span style="color:var(--muted)">/</span><span style="color:var(--cream);font-weight:600">Strongbox</span><span class="badge">Secrets Manager</span></header>
<main><div class="stats"><div class="stat"><div class="stat-value" id="s1">0</div><div class="stat-label">Vaults</div></div><div class="stat"><div class="stat-value" id="s2">0</div><div class="stat-label">Secrets</div></div><div class="stat"><div class="stat-value" id="s3">FREE</div><div class="stat-label">Tier</div></div></div><div class="grid">
<div class="card"><h2>New Vault</h2>
<div class="form-row"><input id="f-vname" placeholder="production-keys"></div>
<div class="form-row"><input id="f-vdesc" placeholder="Description (optional)"></div>
<button class="btn" onclick="createVault()">Create Vault</button></div>
<div class="card"><h2>Vaults</h2><div id="vault-list"><div class="empty">No vaults</div></div></div>
<div class="card full" id="secret-panel" style="display:none">
<h2>Secrets in <span id="vault-label" style="color:var(--cream)"></span></h2>
<div style="display:flex;gap:0.5rem;margin-bottom:1rem;flex-wrap:wrap">
<input id="f-skey" placeholder="SECRET_KEY" style="flex:1"><input id="f-sval" type="password" placeholder="value" style="flex:2"><button class="btn" onclick="upsertSecret()">Set</button></div>
<table><thead><tr><th>Key</th><th>Updated</th><th>Value</th><th></th></tr></thead>
<tbody id="secrets-body"><tr><td colspan="4" class="empty">No secrets</td></tr></tbody></table></div>
</div></main>
<script>
async function api(m,p,bd){var o={method:m,headers:{"Content-Type":"application/json"}};if(bd)o.body=JSON.stringify(bd);var r=await fetch(p,o);try{return await r.json();}catch(e){return {};}}  
var currentVault=null;
async function load(){var s=await api("GET","/api/stats");var l=await api("GET","/api/limits");document.getElementById("s1").textContent=s.vaults||0;document.getElementById("s2").textContent=s.secrets||0;document.getElementById("s3").textContent=(l.tier||"free").toUpperCase();loadVaults();}
async function loadVaults(){var data=await api("GET","/api/vaults");var el=document.getElementById("vault-list");if(!data||!data.length){el.innerHTML="<div class='empty'>No vaults</div>";return;}el.innerHTML=data.map(function(v){return "<div style='display:flex;justify-content:space-between;align-items:center;padding:0.5rem 0;border-bottom:1px solid var(--border)'><span style='cursor:pointer;color:var(--cream)' onclick='selectVault("+v.id+",\""+v.name+"\")'>"+v.name+"<span style='color:var(--muted);font-size:0.75rem'> ("+v.secret_count+" secrets)</span></span><button class='btn btn-sm btn-danger' onclick='deleteVault("+v.id+")'>Del</button></div>";}).join("");}
async function selectVault(id,name){currentVault=id;document.getElementById("secret-panel").style.display="block";document.getElementById("vault-label").textContent=name;loadSecrets();}
async function loadSecrets(){if(!currentVault)return;var data=await api("GET","/api/vaults/"+currentVault+"/secrets");var tbody=document.getElementById("secrets-body");if(!data||!data.length){tbody.innerHTML="<tr><td colspan='4' class='empty'>No secrets</td></tr>";return;}tbody.innerHTML=data.map(function(s){return "<tr><td style='color:var(--cream);font-family:monospace'>"+s.key+"</td><td style='font-size:0.75rem;color:var(--muted)'>"+new Date(s.updated_at).toLocaleDateString()+"</td><td><button class='btn btn-sm' onclick='revealSecret(\""+s.key+"\",this)'>Show</button></td><td><button class='btn btn-sm btn-danger' onclick='deleteSecret("+s.id+")'>Del</button></td></tr>";}).join("");}
async function revealSecret(key,btn){var res=await api("GET","/api/vaults/"+currentVault+"/secrets/"+key);if(res.error){alert(res.error);return;}btn.textContent=res.value;btn.style.color="var(--leather)";setTimeout(function(){btn.textContent="Show";btn.style.color="";},5000);}
async function createVault(){var v={name:document.getElementById("f-vname").value.trim(),description:document.getElementById("f-vdesc").value.trim()};if(!v.name){alert("Name required");return;}var res=await api("POST","/api/vaults",v);if(res.error){alert(res.error);return;}document.getElementById("f-vname").value="";load();}
async function deleteVault(id){if(!confirm("Delete vault and all its secrets?"))return;await api("DELETE","/api/vaults/"+id);currentVault=null;document.getElementById("secret-panel").style.display="none";load();}
async function upsertSecret(){var k=document.getElementById("f-skey").value.trim();var v=document.getElementById("f-sval").value;if(!k){alert("Key required");return;}var res=await api("POST","/api/vaults/"+currentVault+"/secrets",{key:k,value:v});if(res.error){alert(res.error);return;}document.getElementById("f-skey").value="";document.getElementById("f-sval").value="";load();loadSecrets();}
async function deleteSecret(id){if(!confirm("Delete secret?"))return;await api("DELETE","/api/secrets/"+id);loadSecrets();load();}
load();
</script></body></html>`)
